# Generated by Django 5.1.1 on 2024-10-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
